version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bike-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bicycle_maintenance
      POSTGRES_USER: bikemanager
      POSTGRES_PASSWORD: bikemanager123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bike-manager-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bike-manager-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://bikemanager:bikemanager123@postgres:5432/bicycle_maintenance
      JWT_SECRET: your-super-secret-jwt-key-here
      NODE_ENV: production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - bike-manager-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bike-manager-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bike-manager-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  bike-manager-network:
    driver: bridge